### ISSUE TITLE
Feature-bar location on portrait mode

### ISSUE THREAD

**Issue by nagygergo** [nagygergo/PixelFactory#18]
Feature bar is on the left currently. I made it this way since I'm left-handed, and haven't even considered moving it to the right.

***Is it uncanny to use for right-handed people?***

**Comment by kardosorsi** [comment]
The right side is not an usual positioning of the feature list, but probably in this case it's more user friendly as the user holds the phone in his left hand and manipulates the image with his right. Doing so while the feature list is on the left side the user will cover the image with his own hand. I say let's move it to the right side!
